name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  cupertino_icons: ^1.0.6
  characters: ^1.3.0   # Updated
  collection: ^1.18.0   # Updated
  material_color_utilities: ^0.11.1  # Updated
  meta: ^1.15.0   # Updated

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   # Updated
  async: ^2.11.0    # Updated
  boolean_selector: ^2.1.1    # Updated
  clock: ^1.1.1     # Updated
  fake_async: ^1.3.1    # Updated
  leak_tracker: ^10.0.5    # Updated
  leak_tracker_flutter_testing: ^3.0.5  # Updated
  matcher: ^0.12.16+1    # Updated
  path: ^1.9.0    # Updated
  stack_trace: ^1.11.1    # Updated
  string_scanner: ^1.2.0    # Updated

flutter:
  uses-material-design: true
